# Generated by Django 4.2.30 on 2026-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='face_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
